# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(help_text='Hold down "Control", or "Command" on Mac, to select more than one', to='courses.Course'),
        ),
    ]
