"""
Django settings for pybursa project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.contrib import admin

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^bc%e#2^^_4-gelt25qy0wx0vg3i8t3z8e%bi+s(^1^=nxzvx2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'feedbacks.apps.FeedbacksConfig',
    'coaches.apps.CoachesConfig',
    'courses.apps.CoursesConfig',
    'students.apps.StudentsConfig',
    'quadratic.apps.QuadraticConfig',
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware'
]

INTERNAL_IPS = ['127.0.0.1']

ROOT_URLCONF = 'pybursa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pybursa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

admin.site.site_header = 'PyBursa Administration'

EMAIL_HOST = '127.0.0.1'
EMAIL_PORT = '1025'

ADMINS = [('Viacheslav Kovalenko', 'kovalenko_v@gmail.com')]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
        'file_courses_debug': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'courses_logger.log',
            'formatter': 'simple'
        },
        'file_courses_info': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'courses_logger.log',
            'formatter': 'simple'
        },
        'file_courses_warning': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': 'courses_logger.log',
            'formatter': 'simple'
        },
        'file_courses_error': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'courses_logger.log',
            'formatter': 'simple'
        },
        'file_students_debug': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'students_logger.log',
            'formatter': 'verbose'
        },
        'file_students_info': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'students_logger.log',
            'formatter': 'verbose'
        },
        'file_students_warning': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': 'students_logger.log',
            'formatter': 'verbose'
        },
        'file_students_error': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'students_logger.log',
            'formatter': 'verbose'
        },
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(funcName)s %(message)s'
        },
        'simple': {
            'format': '%(levelname)s: %(message)s'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'courses': {
            'handlers': ['console', 'file_courses_debug', 'file_courses_info',
                         'file_courses_warning', 'file_courses_error'],
            'level': 'DEBUG'
        },
        'students': {
            'handlers': ['console', 'file_students_debug', 'file_students_info',
                         'file_students_warning', 'file_students_error'],
            'level': 'WARNING'
        },
    },
}