# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
