# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='form_email',
            new_name='from_email',
        ),
    ]
