# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_auto_20170904_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
