from django.db import models

from courses.models import Course

class Student(models.Model):
    name = models.CharField(max_length = 50)
    surname = models.CharField(max_length = 50)
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone = models.CharField(max_length = 50)
    address = models.CharField(max_length = 120)
    skype = models.CharField(max_length = 64)
    courses = models.ManyToManyField(Course)
    
    def full_name(self):
        return self.name + ' ' + self.surname

    def get_all_model_field_names(self):
        '''
        Returns all fields as list without autogenerated
        '''
        result = []
        for field in self._meta.get_fields():
            if not field.auto_created:
                result.append(field.name)

        return result
